version: "3.8"
services:
  app:
    image: sveltekit
    build:
      dockerfile: Dockerfile.dev
      context: ./app
    volumes:
      - ./app:/home/node/app # Drop all our code from ./app into container's usr/src/app directory 
      - sveltekit-output:/home/node/app/.svelte-kit
    ports:
      - "5173:5173"
    command:
      # Copy node_modules into volume-mounted directory so we can see them in dev environment
      [
        sh,
        -c,
        "cp -r /home/node/cache/. /home/node/app/. && npm run dev -- --host"
      ]

  backend:
    image: firebase
    build:
      context: ./firebase
      dockerfile: Dockerfile.dev
    ports:
      - 4000:4000
      - 8080:8080
      - 5000:5000
    volumes:
      - ./firebase:/app
      - sveltekit-output:/app/anothertest

volumes:
  sveltekit-output:
