name: Deploy
on:
  push:
    branches:
    - main

jobs:
  build:
    name: Deploy to Firebase
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@master
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only firestore
      env:
        GCP_SA_KEY: ${{ secrets.TEST_KEY }}
        PROJECT_PATH: ./firebase
