name: Deploy
on:
  push:
    branches:
    - master

jobs:
  build:
    name: Deploy to Firebase
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@master
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only firestore
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SVELTEKIT_FIREBASE_1E60F }}
        PROJECT_PATH: ./firebase
